language: go

matrix:
  include:
    - os: osx
      go: "1.12"
      script: make
    - os: linux
      go: "1.11"
      script: make
    - os: linux
      go: "1.12"
      script: make
    - os: linux
      go: tip
      script: make
    - os: linux
      go: "1.12"
      services:
        - docker
      dist: xenial
      sudo: true
      language: c
      env: DOCKER_BUILD=1
      script: |
        echo "===== BUILD DOCKER IMAGE ======="
        docker build . -t fluent-bit/loki-plugin
