version: v0-winbuild-{build}

build: off

clone_folder: c:\gopath\src\github.com\cosmo0920\fluent-bit-go-loki

environment:
  GOPATH: c:\gopath
  PATH: C:\msys64\mingw64\bin\;%PATH%

stack: go 1.11

before_test:
  - go vet ./...

test_script:
  - go test ./... -v
  - go build -buildmode=c-shared -o out_loki.dll .
  - 7z a fluent-bit-go-loki.zip out_loki.dll
  - set ARTIFACT=fluent-bit-go-loki.zip

on_success:
  - ps: Push-AppveyorArtifact $Env:ARTIFACT

artifacts:
  - path: fluent-bit-go-loki.zip
    name: binary

deploy:
  provider: GitHub
  auth_token:
    secure: 7XdoaFISgIXPlmVTNkMMS5cOhQzCQ06N1ksjNsres/dAyMYbT8CTxnV9KgHabwww
  artifact: binary          # upload zip archive to release assets
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
